### ISSUE TITLE
Can I use a different session?

### ISSUE THREAD

**Issue by ursm** [adopted-ember-addons/ember-electron#275] opened 2017-06-27 01:30 UTC
I want to use different sessions in the development environment and test environment to avoid localStorage conflicts. For this I made the following modifications to the code.

``` diff
diff --git a/tests/ember-electron/main.js b/tests/ember-electron/main.js
index 042ae03..d48352a 100644
--- a/tests/ember-electron/main.js
+++ b/tests/ember-electron/main.js
@@ -46,6 +46,9 @@ app.on('ready', function onReady() {
     width: 800,
     height: 600,
     backgroundThrottling: false,
+    webPreferences: {
+      partition: 'test'
+    }
   });

   delete mainWindow.module;
```

However, running `ember electron:test` opens a blank window. In the developer tool, the value of `location.href` is `about:blank`.

Could you give me some advice?

**Comment by bendemboski** [comment] 2017-12-02 23:28
The root cause of this is described in [this](https://github.com/electron/electron/issues/7383) issue. `electron-protocol-serve` registers a file protocol on the default partition, so for this to work you'd need to be able to tell it to also register the protocol on your custom partition. [this](https://github.com/pichfl/electron-protocol-serve/issues/5) issue describes what would be needed in `electron-protocol-serve`, so this issue is blocked on resolving that issue.

**Comment by bendemboski** [comment] 2019-11-26 02:53
Closing due to inactivity

**Closed by bendemboski** 2019-11-26 02:53 UTC
Labels: bug, upstream tooling
