### ISSUE TITLE
Cannot run ember electron:package 

### ISSUE THREAD

**Issue by AhmadIbrahiim** [adopted-ember-addons/ember-electron#440] opened 2020-01-06 12:31 UTC
I have been trying to package an ember/electron app but when I try to  hit `ember electron:package `
I get the below error 
![image](https://user-images.githubusercontent.com/17949497/71818158-daa6a680-3090-11ea-99b0-348909eaf2bc.png)
```

error dumb : 
=================================================================================

ENV Summary:

  TIME: Mon Jan 06 2020 14:23:16 GMT+0200 (Eastern European Standard Time)
  TITLE: ember
  ARGV:
  - /home/ahmed/.nvm/versions/node/v10.17.0/bin/node
  - /home/ahmed/.nvm/versions/node/v10.17.0/bin/ember
  - electron:package
  EXEC_PATH: /home/ahmed/.nvm/versions/node/v10.17.0/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /home/ahmed/.nvm/versions/node/v10.17.0/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  PLATFORM: linux x64
  FREEMEM: 838516736
  TOTALMEM: 8247717888
  UPTIME: 171188
  LOADAVG: 3.30078125,2.53564453125,2.5146484375
  CPUS:
  - Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz - 2417
  - Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz - 2417
  - Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz - 2417
  - Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz - 2417
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 35.1
  - http_parser: 2.8.0
  - icu: 64.2
  - modules: 64
  - napi: 5
  - nghttp2: 1.39.2
  - node: 10.17.0
  - openssl: 1.1.1d
  - tz: 2019a
  - unicode: 12.1
  - uv: 1.28.0
  - v8: 6.8.275.32-node.54
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Command failed with exit code 1: npm install --production --no-bin-links
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Command failed with exit code 1: npm install --production --no-bin-links
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Command failed with exit code 1: npm install --production --no-bin-links
    at makeError (/home/ahmed/Desktop/MaxmioTech/linkedtools/node_modules/ember-electron/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/home/ahmed/Desktop/MaxmioTech/linkedtools/node_modules/ember-electron/node_modules/execa/index.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)

=================================================================================

```

When I run `npm install --production --no-bin-links` without electron build ` without electron it works really well.

I'm not sure what is the problem

**Comment by rwwagner90** [comment] 2020-01-06 12:32
What version of ember-electron are you using and how did you install it?

**Comment by AhmadIbrahiim** [comment] 2020-01-06 12:38
@rwwagner90  I'm using ember-electron  of  ` {"ember-electron": "^2.10.2"}
`
and I have installed it throught : `ember install ember-electron`

**Comment by jacobq** [comment] 2020-01-06 13:02
I assume you get the same failure with `ember electron:make`, is that right?

**Comment by AhmadIbrahiim** [comment] 2020-01-06 13:16
> I assume you get the same failure with `ember electron:make`, is that right?

@jacobq  Yes. That's correct I'm getting this error with all ember electron:<WHATEVER>

**Comment by jacobq** [comment] 2020-01-06 13:49
Here're some additional things I would try if I were in your shoes:

0. Delete `node_modules` and reinstall -- assume you already tried that to no avail
1. Run with `DEBUG` env var set to enable some logging, e.g. `DEBUG=ember-cli:*,*electron*,-*babel* ember electron:package`. This may give some more context. Note also that when you're running those `ember electron:XYZ` commands (at least on 2.x) I think the `npm install ...` you're seeing is not the one in the root project folder but rather in the electron project output, so your comment saying "When I run npm install --production --no-bin-links without electron build ` without electron it works really well." may be a case of this confusing detail getting the best of you.
2. Try to reproduce in a new/empty project -- if the problem still happens feel free to share the repo here or add steps to reproduce it. Then I or someone else can see if the problem happens for us also or is specific to the machine you're using.
3. Try using the 3.x beta release -- it has quite a few improvements and I am using it without problems.

**Comment by AhmadIbrahiim** [comment] 2020-01-06 14:01
@jacobq  Do you think the linter error could make an issue like this?

**Comment by rwwagner90** [comment] 2020-01-06 14:04
I would try the 3.x beta and see if things fix themselves.

**Comment by AhmadIbrahiim** [comment] 2020-01-06 14:07
> I would try the 3.x beta and see if things fix themselves.

@rwwagner90  Do you mean 3.x beta of ember electron?

**Comment by rwwagner90** [comment] 2020-01-06 14:09
@AhmadIbrahiim yes

**Comment by jacobq** [comment] 2020-01-06 14:26
> @jacobq Do you think the linter error could make an issue like this?

First I want to see what is going wrong. If the cause turns out to be easy to check for then I'd be in favor of making the output messages help detect and correct it.

**Comment by AhmadIbrahiim** [comment] 2020-01-06 14:40
@rwwagner90  @jacobq  This what happen when I upgraded to 3.x beta
![image](https://user-images.githubusercontent.com/17949497/71824858-26624b80-30a3-11ea-9d1b-a0d20ea9b3b5.png)

**Comment by rwwagner90** [comment] 2020-01-06 15:14
@AhmadIbrahiim yeah, as the message says, you'll need to update your project format.

**Comment by jacobq** [comment] 2020-01-06 17:26
> ...you'll need to update your project format.

Yes, 3.x has breaking changes. If you want to use it, please check out the migration docs:
https://ember-electron.js.org/versions/v3.0.0-beta.1/docs/guides/upgrading

**Comment by bendemboski** [comment] 2020-01-08 18:28
I'm going to close this issue as it's not currently actionable (and we're not likely to spend effort fixing bugs on 2.x). Feel free to continue the support request/discussion on the closed issue, or re-open if you find it still happens on 3.x.

**Closed by bendemboski** 2020-01-08 18:28 UTC
