### ISSUE TITLE
ember-electron 3 beta and ember inspector

### ISSUE THREAD

**Issue by basz** [adopted-ember-addons/ember-electron#630] opened 2020-11-02 09:28 UTC
Hi,

I've been successful in setting up an ember project targeting win32 and darwin after moving to ember-electron 3-beta. A pretty solid road! 🎆 

One thing that seems to fail is getting the ember inspector working. It seems to be able to that an update to devtron is required but that package is currently unmaintained. I just wanted to check in and see if anyone got ember inspector working or are we simply out of luck on that front for the time being?

Thanks!

**Comment by rwwagner90** [comment] 2020-11-02 16:02
This is a known issue.

Duplicate of https://github.com/adopted-ember-addons/ember-electron/issues/532 and https://github.com/adopted-ember-addons/ember-electron/issues/359

**Comment by rwwagner90** [comment] 2020-11-02 16:03
Devtron is unrelated to ember-inspector, but something needs to be updated in ember-inspector to work with Electron. My guess is it doesn't like file urls is part of the problem.

**Closed** 2020-11-02 16:02 UTC
Labels: duplicate
